# Generated by Django 4.2.16 on 2024-12-02 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0002_userinedition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_start_date', models.DateTimeField()),
                ('voting_end_date', models.DateTimeField()),
                ('results_date', models.DateTimeField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Final',
            fields=[
                ('phase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phases.phase')),
            ],
            bases=('phases.phase',),
        ),
        migrations.CreateModel(
            name='Semifinal',
            fields=[
                ('phase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phases.phase')),
                ('count', models.PositiveIntegerField()),
                ('number_of_countries_qualify', models.PositiveIntegerField()),
            ],
            bases=('phases.phase',),
        ),
    ]
