# Generated by Django 4.2.16 on 2025-03-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0003_edition_actual_edition_name_edition_postponed_and_more'),
        ('phases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='edition',
        ),
        migrations.AddField(
            model_name='final',
            name='edition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.edition'),
        ),
        migrations.AddField(
            model_name='semifinal',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.edition'),
        ),
    ]
