# Generated by Django 4.2.16 on 2025-03-28 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_remove_entryinphase_entry_entryinfinal_entry_and_more'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.entryinphase'),
        ),
    ]
