# Generated by Django 4.2.16 on 2025-03-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_userincontest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
