# Generated by Django 4.2.16 on 2025-03-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_alter_contest_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInContest',
        ),
    ]
