# Generated by Django 4.2.16 on 2025-04-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_delete_userincontest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
    ]
