# Generated by Django 4.2.16 on 2025-03-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0002_userinedition'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='postponed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edition',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
