# Generated by Django 4.2.16 on 2025-04-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0003_edition_actual_edition_name_edition_postponed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='claiming_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='claiming_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='sending_songs_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='sending_songs_start',
            field=models.DateTimeField(null=True),
        ),
    ]
