# Generated by Django 4.2.16 on 2025-03-11 12:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryinedition',
            name='borrowers',
        ),
        migrations.AlterField(
            model_name='countryinedition',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AddField(
            model_name='countryinedition',
            name='borrowers',
            field=django_countries.fields.CountryField(default=[], max_length=746, multiple=True),
        ),
    ]
