# Generated by Django 4.2.16 on 2025-03-12 19:39

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_remove_countryinedition_borrowers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryinedition',
            name='borrowers',
            field=django_countries.fields.CountryField(blank=True, default=[], max_length=746, multiple=True),
        ),
    ]
