# Generated by Django 4.2.16 on 2024-11-25 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artists', models.JSONField(default=[])),
                ('title', models.CharField(max_length=255)),
                ('Youtube_URL', models.URLField()),
                ('Spotify_URL', models.URLField()),
                ('ts', models.TimeField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.edition')),
            ],
        ),
    ]
