# Generated by Django 4.2.16 on 2025-03-12 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0001_initial'),
        ('entries', '0003_remove_entry_artists_entry_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryInPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_order', models.PositiveIntegerField()),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entries.entry')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phases.phase')),
            ],
        ),
    ]
