# Generated by Django 4.2.16 on 2025-03-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0002_remove_phase_edition_final_edition_semifinal_edition'),
        ('entries', '0005_entryinfinal_entryinsemifinal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryinphase',
            name='phase',
        ),
        migrations.AddField(
            model_name='entryinfinal',
            name='final',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phases.final'),
        ),
        migrations.AddField(
            model_name='entryinsemifinal',
            name='semifinal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phases.semifinal'),
        ),
    ]
