# Generated by Django 4.2.16 on 2025-03-27 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_remove_entryinphase_phase_entryinfinal_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryinphase',
            name='entry',
        ),
        migrations.AddField(
            model_name='entryinfinal',
            name='entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.entry'),
        ),
        migrations.AddField(
            model_name='entryinsemifinal',
            name='entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.entry'),
        ),
    ]
