# Generated by Django 4.2.16 on 2025-04-06 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_countryinedition_user'),
        ('entries', '0007_remove_entryinphase_entry_entryinfinal_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
        migrations.AddField(
            model_name='entry',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.countryinedition'),
        ),
    ]
