# Generated by Django 4.2.16 on 2025-04-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_remove_entry_user_entry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryinphase',
            name='running_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
