# Generated by Django 4.2.16 on 2025-05-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_entry_additional_info_entry_comment_entry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.IntegerField(choices=[(None, 'Do rozpatrzenia'), (0, 'Odrzucone'), (1, 'Zaakceptowane')], null=True),
        ),
    ]
